[package]
name = "n_body"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
bevy = "0.11.1"
bigbang = "0.0.11"
rand = "0.8.5"
